apiVersion: v1
kind: Service
metadata:
  name: my-nginx-test
  labels:
    run: my-nginx-test
spec:
  type: NodePort
  ports:
  - nodePort: 32080
    port: 80
    protocol: TCP
  selector:
    run: my-nginx-test
